name: spam_classifier_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.9
  - django
  - djangorestframework
  - gunicorn
  - numpy
  - pandas
  - scikit-learn
  - gensim
  - joblib
  - pip
  - pip:
      - django-cors-headers
